/** @format */

export default {
  "Exit": "Salir",
  "ExitConfirm": "¿Seguro que desea salirse de la aplicación?",
  "YES": "SI",
  "OK": "OK",
  "ViewMyOrders": "Ver mis órdenes",
  "CANCEL": "CANCELAR",
  "Confirm": "Confirmar",

  // Scene's Titles
  "Home": "Inicio",
  "Intro": "Introducción",
  "Product": "Producto",
  "Cart": "Carrito",
  "WishList": "Lista de Deseos",
  "ProductCategories": "Categorías",
  "UserProfile": "Perfil",
  "Address": "Direcciones",
  "AddAddress": "Crear dirección",
  "UpdateAddress": "Editar dirección",
  "OrderDetailsTitle": "Detalles del pedido",
  "MyOrdersTitle": "Mis pedidos",
  "ContactUs": "Contáctanos",
  "MyCardsTitle": "tarjetas",
  "Notifications" : "Notificaciones",

  // Home
  "products": "Productos",

  // TopBarz
  "ShowFilter": "Sub categoria",
  "HideFilter": "Esconder",
  "Sort": "Ordenar",
  "textFilter": "Reciente",

  // Category
  "ThereIsNoMore": "No disponible en este momento.",

  // Product
  "AddtoCart": "Agregar al carrito",
  "AddtoWishlist": "Agregar a la Lista de Deseos",
  "ProductVariations": "Variaciones",
  "NoVariation": "No hay otra variación de este producto",
  "AdditionalInformation": "Descripción",
  "NoProductDescription": "No hay descripción de producto",
  "ProductReviews": "Comentarios",
  "NoReview": "Este producto no cuenta con comentarios, por el momento",
  "BUYNOW": "COMPRAR AHORA",
  "OutOfStock": "NO DISPONIBLE EN ESTE MOMENTO",
  "ProductLimitWaring": "Únicamente contamos con {num} unidades disponibles",
  "EmptyProductAttribute": "Este producto no cuenta con atributos",
  "ProductFeatures": "Características",
  "ErrorMessageRequest": "No se puede comunicar con el servidor",
  "NoConnection": "Sin conexión a internet",
  "ProductRelated": "Productos relacionados",

  // Cart
  "NoCartItem": "No hay productos en el carrito",
  "Total": "Total",
  "EmptyCheckout": "Lo sentimos, no se puede proceder con el carrito vació",
  "RemoveCartItemConfirm": "¿Quitar este producto del carrito?",
  "MyCart": "Mi carrito",
  "Order": "Orden",
  "ShoppingCart": "Carrito de compras",
  "ShoppingCartIsEmpty": "Tu carrito está vacío",
  "AddProductToCart": "Agregar producto al carrito",
  "TotalPrice": "Gran total",
  "YourDeliveryInfo": "Detalles de envío",
  "ShopNow": "Ir a comprar",
  "YourChoice": "Mi carrito:",
  "YourSale": "Mis compras:",
  "SubtotalPrice": "Subtotal:",
  "BuyNow": "Comprar ahora",
  "Items": "artículos",
  "Item": "artículo",
  "ThankYou": "Muchas gracias \npor tu compra",
  "FinishOrderCOD": "Puedes utilizar este número de orden para seguir tu pedido",
  "FinishOrder": "Para verificar el status de envío por favor ve a Mis Órdenes. Tu pedido llegará mañana {date} después de confirmado.",
  "NextStep": "Siguiente Paso",
  "ConfirmOrder": "Confirmar Orden",
  "RequireEnterAllFileds": "Por favor ingresar todos los campos",
  "Error": "Error",
  "InvalidEmail": "Correo no válido",
  "Finish": "Finalizar",
  "MinimumOrderAmount": "Tu total debe ser mayor a Q60 para poder continuar.",
  "labelOrder": "Tu pedido llegará mañana {date} después de confirmado. \nPedido mínimo: Q60.00 ",
  "labelOrder2": "Tu pedido llegará al siguiente día después de confirmado. \nPedido mínimo: Q60.00",
  "labeldrink": "Decreto 90-97 \"El exceso en el consumo de este producto causa serios daños a la salud\". ",
  // Wishlist
  "NoWishListItem": "No hay ningún artículo en tu Lista de Deseos",
  "MoveAllToCart": "Mover todo al carrito",
  "EmptyWishList": "Vaciar mi Lista de Deseos",
  "EmptyAddToCart": "Lo sentimos, la Lista de Deseos está vacía",
  "RemoveWishListItemConfirm": "¿Deseas remover este artículo de tu Lista de Deseos?",
  "CleanAll": "Vaciar todo",

  // Sidemenu
  "SignIn": "Ingresar",
  "SignOut": "Salir",
  "GuestAccount": "Mi cuenta",
  "CantReactEmailError": "No hemos podido ingresar por tu correo electrónico, por favor intenta otra método de ingreso",
  "NoEmailError": "Tu cuenta no tiene un correo electrónico válido",
  "EmailIsNotVerifiedError": "Tu correo electrónico no ha sido verificado",
  "Login": "Ingresar",
  "Logout": "Salir",
  "Shop": "Comprar",
  "Category": "Categorías",

  // Checkout
  "Checkout": "Pagar ahora",
  "ProceedPayment": "Proceder al pago",
  "Purchase": "Comprar",
  "CashOnDelivery": "Efectivo contra entrega",
  "CreditCard": "Tarjeta de crédito",
  "PaymentMethod": "Método de pago no seleccionado",
  "PaymentMethodError": "Por favor elegir tu método de pago",
  "PayWithCoD": "Tu compra será pagada contra entrega",
  "PayWithPayPal": "Tu compra será pagada con Paypal",
  "Paypal": "Paypal",
  "Stripe": "Stripe",
  "PayWithStripe": "Tu compra será pagada con Stripe",
  "ApplyCoupon": "Aplicar",
  "CouponPlaceholder": "Código de descuento",
  "Apply": "Aplicar",
  "Applying": "Aplicando",
  "Back": "Regresar",
  "CardNamePlaceholder": "Nombre en la tarjeta",
  "BackToHome": "Regresar al inicio",
  "OrderCompleted": "Tu orden ha sido completada",
  "OrderCanceled": "Tu orden ha sido cancelada",
  "OrderFailed": "Algo salió mal…",
  "OrderCompletedDesc": "Tu número de orden es",
  "OrderCanceledDesc": "La transacción no fue completada, por favor cancelar tu orden",
  "OrderFailedDesc": "Hemos encontrado un error al intentar procesar tu orden. La transacción no ha sido completada. Por favor inténtalo de nuevo.",
  "OrderTip": "Tip: Puedes rastrear tu orden en la sección de \"Mis Órdenes\" en el menú del lado",
  "Delivery": "Envío",
  "Payment": "Pago",
  "Complete": "Completado",
  "EnterYourFirstName": "Ingresa tu nombre",
  "EnterYourLastName": "Ingresa tu apellido",
  "EnterYourEmail": "Ingresa tu correo electrónico",
  "EnterYourPhone": "Ingresa tu número de teléfono",
  "EnterYourAddress": "Ingresa tu dirección",
  "CreateOrderError": "No se ha podido crear la orden. Por favor inténtalo más tarde",


  // myorder
  "OrderId": "ID de la orden",
  "MyOrder": "Mi Orden",
  "NoOrder": "No tienes ninguna orden",
  "OrderDate": "Fecha de orden",
  "OrderStatus": "Estado",
  "OrderPayment": "Método de pago:",
  "OrderTotal": "Tota:",
  "OrderDetails": "Ver detalles:",
  "OrderLineItems": "Artículos:",
  "ShippingAddress": "Dirección de entrega:",
  "Refund": "Reembolso",
  "cancelled": "Cancelada",
  "processing": "En proceso",
  "completed": "Completado",
  "invoiced": "Facturado",
  "pending": "Pendiente de pago",

  "News": "Noticias",
  "PostDetails": "Detalles",
  "FeatureArticles": "Artículos destacados",
  "MostViews": "Más vistos",
  "EditorChoice": "Nuestra selección",

  // settings
  "Settings": "Ajustes",
  "BASICSETTINGS": "AJUSTES BÁSICOS",
  "Language": "Idioma",
  "INFO": "INFO",
  "About": "Acerca de nosotros",
  "faqs": "Preguntas frecuentes",

  // language
  "AvailableLanguages": "Idiomas disponibles",
  "SwitchLanguage": "Cambiar idioma",
  "SwitchLanguageConfirm": "Para cambiar el idioma necesitamos cargar de nuevo la aplicación, ¿deseas continuar?",

  // about us
  "AppName": "Devolá",
  "AppDescription": "Tema para mCommerce de React Native",
  "AppContact": "Contáctanos en: https://devola.gt",
  "AppEmail": "Correo electrónico: ayuda@devola.gt",
  "AppCopyRights": "© Devolá 2020",

  // contact us
  "contactus": "Contáctanos",

  // form
  "NotSelected": "Sin seleccionar",
  "EmptyError": "Este campo está vacío",
  "DeliveryInfo": "Información de envío",
  "FirstName": "Nombre",
  "NameAddres": "Nombre de direccion",
  "LastName": "Apellido",
  "Address": "Dirección",
  "City": "Municipio",
  "State": "Departamento",
  "NotSelectedError": "Por favor elige una opción",
  "Postcode": "Código postal",
  "zone": "zona",
  "Country": "País",
  "Email": "Correo Electrónico",
  "Phone": "Número de teléfono",
  "Note": "Notas",
  "municipality":"Municipio",
  "zone": "Zona",

  "nit": "Nit",
  "correoAlterno": "Correo electrónico 2",
  // search
  "Search": "Buscar",
  "SearchPlaceHolder": "Buscar por nombre",
  "NoResultError": "No hemos encontrado nada relacionado con tu búsqueda",
  "Details": "Detalles",

  // filter panel
  "Categories": "Categorías",
  "Loading": "CARGANDO…",
  "welcomeBack": "¡Bienvenido de vuelta!",
  "seeAll": "Mostrar todo",

  // Layout
  "cardView": "Tarjeta",
  "simpleView": "Vista en lista",
  "twoColumnView": "Dos Columnas",
  "threeColumnView": "Tres Columnas",
  "listView": "Vista en lista",
  "default": "Predeterminado",
  "advanceView": "Avanzar",
  "horizontal": "Horizontal",

  "couponCodeIsExpired": "Este código de descuento ha expirado",
  "invalidCouponCode": "Este código de descuento no es válida",
  "remove": "Quitar",
  "applyCouponSuccess": "¡Felicidades! El código ha sido aplicado exitósamente. ",
  "reload": "Refrescar",

  "ShippingType": "Método de envío",
  "BillingDetail": "Detalles de Facturación",

  // Place holder
  "TypeFirstName": "Ingresa tu nombre",
  "TypeNameAddress": "Ingresa el nombre de la dirección",
  "TypeLastName": "Ingresa tu apellido",
  "TypeAddress": "Ingresa tu dirección",
  "TypeCity": "Ingresa tu ciudad",
  "TypeState": "Ingresa tu departamento",
  "TypeNotSelectedError": "Por favor elige una opción",
  "TypePostcode": "Ingreso tu código postal",
  "TypeZone": "Ingresa tu zona",
  "TypeEmail": "Ingresa tu correo electrónico (eje. abc@gmail.com)",
  "TypePhone": "Ej. 9999-9999",
  "TypeNote": "Notas",
  "TypeCountry": "Elige tu país",
  "SelectPayment": "Elige tu método de pago",
  "close": "CERRAR",
  "noConnection": "SIN ACCESO A INTERNET",
  "TypeNit": "Ingresa tu nit",
  "TypeMunicipality": "Ingresa tu municipio",

  // user profile screen
  "AccountInformations": "Información de tu cuenta",
  "PushNotification": "Notificaciones",
  "DarkTheme": "Tema Oscuro",
  "Privacy": "Políticas de privacidad",
  "SelectCurrency": "Elige tu moneda",
  "Name": "Nombre",
  "Currency": "Moneda",
  "Languages": "Idiomas",
  "Guest": "Visitante",
  "FacebookLogin": "Continuar con Facebook",
  "GoogleLogin": "Continuar con Google",
  "AppleLogin": "Continuar con Apple",
  "Or": "o",
  "UserOrEmail": "Usuario o correo electrónico",
  "DontHaveAccount": "¿No tienes una cuenta?",
  "accountDetails": "Detalles de tu cuenta",
  "username": "Usuario",
  "email": "Correo electrónico",
  "generatePass": "Generar contraseña",
  "password": "Contraseña",
  "signup": "Registrarme",
  "profileDetail": "Detalles de mi usuario",
  "firstName": "Nombre",
  "lastName": "Apellido",

  // Horizontal
  "featureProducts": "Artículos destacados",
  "bagsCollections": "Colección de bolsas",
  "blog": "Blog",
  "womanBestSeller": "Más vendido",
  "manCollections": "Colección para hombres",

  // Modal
  "Select": "Seleccionar",
  "Cancel": "Cancelar",

  // review
  "vendorTitle": "Vendedor",
  "comment": "Dejar un comentario",
  "yourcomment": "Tu comentario",
  "placeComment": "Cuéntanos sobre tu experiencia",
  "writeReview": "Comentarios",
  "thanksForReview": "Gracias por tu comentario",
  "errInputComment": "Por favor ingresa tu comentario",
  "errRatingComment": "Por favor evalúa para proceder",
  "send": "Enviar",
  "termCondition": "Términos y condiciones",
  "Subtotal": "Subtotal",
  "Discount": "Descuento",
  "Shipping": "Envío",
  "Recents": "Reciente",
  "Filters": "Filtros",
  "Pricing": "Precio",
  "Filter": "Filtro",
  "ClearFilter": "Borrar Filtro",
  "ProductCatalog": "Categorías de productos",
  "ProductTags": "Etiquetas de prodcutos",
  "AddToAddress": "Agregar dirección de entrega",
  "UpdateAddressButton": "Actualizar dirección de entrega",
  "OrderNotes": "Notas de entrega",
  "Sort": "Ordenar",
  "sendComment": "Enviar comentarios",
  "sendEvaluation": "Enviar evaluación",
  "noThanks": "No, gracias",
  "TypeSurvey": "Escríbenos qué marca o qué tipo de productos necesitas para que los incorporemos...",
  "seeOrden": "Tu carrito",
  "again": "Pedir otra vez",
  "accept": "ACEPTAR",
  "continues": "Continuar con tu pedido",
  "MyCards": "Tarjetas"
};
